Irssi updates.

diff --git a/irssi/config b/irssi/config
--- a/irssi/config
+++ b/irssi/config
@@ -2,73 +2,80 @@ servers = (
   {
     address = "irc.recycled-irc.net";
     chatnet = "RecycledIRC";
-    port = "6667";
+    port    = "6667";
   },
   {
     address = "irc.irchighway.net";
     chatnet = "IRCHighway";
-    port = "6667";
+    port    = "6667";
+  },
+  {
+    address = "irc.freenode.net";
+    chatnet = "Freenode";
+    port    = "6667";
   }
 );
 
 chatnets = {
-  IRCHighway = { type = "IRC"; };
+  IRCHighway  = { type = "IRC"; };
   RecycledIRC = { type = "IRC"; };
+  Freenode    = { type = "IRC"; };
 };
 
 channels = (
   { name = "#infexious"; chatnet = "RecycledIRC"; autojoin = "Yes"; },
-  { name = "#ebooks"; chatnet = "IRCHighway"; autojoin = "Yes"; }
+  { name = "#ebooks"; chatnet = "IRCHighway"; autojoin = "Yes"; },
+  { name = "#relayfm"; chatnet = "Freenode"; autojoin = "Yes"; }
 );
 
 aliases = {
-  J = "join";
-  WJOIN = "join -window";
-  WQUERY = "query -window";
-  LEAVE = "part";
-  BYE = "quit";
-  EXIT = "quit";
-  SIGNOFF = "quit";
-  DESCRIBE = "action";
-  DATE = "time";
-  HOST = "userhost";
-  LAST = "lastlog";
-  SAY = "msg *";
-  WI = "whois";
-  WII = "whois $0 $0";
-  WW = "whowas";
-  W = "who";
-  N = "names";
-  M = "msg";
-  T = "topic";
-  C = "clear";
-  CL = "clear";
-  K = "kick";
-  KB = "kickban";
-  KN = "knockout";
-  BANS = "ban";
-  B = "ban";
-  MUB = "unban *";
-  UB = "unban";
-  IG = "ignore";
-  UNIG = "unignore";
-  SB = "scrollback";
-  UMODE = "mode $N";
-  WC = "window close";
-  WN = "window new hide";
-  SV = "say Irssi $J ($V) - http://irssi.org/";
-  GOTO = "sb goto";
-  CHAT = "dcc chat";
-  RUN = "SCRIPT LOAD";
-  CALC = "exec - if command -v bc >/dev/null 2>&1\\; then printf '%s=' '$*'\\; echo '$*' | bc -l\\; else echo bc was not found\\; fi";
-  SBAR = "STATUSBAR";
-  INVITELIST = "mode $C +I";
-  Q = "QUERY";
+  J                = "join";
+  WJOIN            = "join -window";
+  WQUERY           = "query -window";
+  LEAVE            = "part";
+  BYE              = "quit";
+  EXIT             = "quit";
+  SIGNOFF          = "quit";
+  DESCRIBE         = "action";
+  DATE             = "time";
+  HOST             = "userhost";
+  LAST             = "lastlog";
+  SAY              = "msg *";
+  WI               = "whois";
+  WII              = "whois $0 $0";
+  WW               = "whowas";
+  W                = "who";
+  N                = "names";
+  M                = "msg";
+  T                = "topic";
+  C                = "clear";
+  CL               = "clear";
+  K                = "kick";
+  KB               = "kickban";
+  KN               = "knockout";
+  BANS             = "ban";
+  B                = "ban";
+  MUB              = "unban *";
+  UB               = "unban";
+  IG               = "ignore";
+  UNIG             = "unignore";
+  SB               = "scrollback";
+  UMODE            = "mode $N";
+  WC               = "window close";
+  WN               = "window new hide";
+  SV               = "say Irssi $J ($V) - http://irssi.org/";
+  GOTO             = "sb goto";
+  CHAT             = "dcc chat";
+  RUN              = "SCRIPT LOAD";
+  CALC             = "exec - if command -v bc >/dev/null 2>&1\\; then printf '%s=' '$*'\\; echo '$*' | bc -l\\; else echo bc was not found\\; fi";
+  SBAR             = "STATUSBAR";
+  INVITELIST       = "mode $C +I";
+  Q                = "QUERY";
   "MANUAL-WINDOWS" = "set use_status_window off;set autocreate_windows off;set autocreate_query_level none;set autoclose_windows off;set reuse_unused_windows on;save";
-  EXEMPTLIST = "mode $C +e";
-  ATAG = "WINDOW SERVER";
-  UNSET = "set -clear";
-  RESET = "set -default";
+  EXEMPTLIST       = "mode $C +e";
+  ATAG             = "WINDOW SERVER";
+  UNSET            = "set -clear";
+  RESET            = "set -default";
 };
 
 statusbar = {
